name: Upload SARIF to GitHub Code Scanning

on:
  push:
    branches: [main]

jobs:
  upload-sarif:
    name: Upload SARIF Report
    runs-on: ubuntu-latest
    steps:
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ori.sarif.json